// ─── CONTENT DATA — expanded ─────────────────────────────────────

const TOPICS = [
  { id: 'idioms',       n: '01', title: 'Idioms',            subtitle: 'Native-speaker phrases',          mark: 'I',  lessons: 4 },
  { id: 'language',     n: '02', title: 'Using Language',    subtitle: 'Talk shop, cross-purposes',       mark: 'L',  lessons: 3 },
  { id: 'emphasising',  n: '03', title: 'Emphasising',       subtitle: 'Bone dry, rock hard',             mark: 'E',  lessons: 3 },
  { id: 'opposites',    n: '04', title: 'Opposites',         subtitle: 'Un-, in-, dis-, im-, ir-',        mark: 'O',  lessons: 3 },
  { id: 'freetime',     n: '05', title: 'Free Time & Leisure', subtitle: 'Rewarding, therapeutic, hooked on', mark: 'F', lessons: 3 },
  { id: 'colours',      n: '06', title: 'Colour',            subtitle: 'Shades, metaphors, idioms',       mark: 'C',  lessons: 4 },
  { id: 'conditionals', n: '07', title: 'Conditionals',      subtitle: 'If-clauses, all types',           mark: 'N',  lessons: 3 },
  { id: 'inversions',   n: '08', title: 'Inversions',        subtitle: 'Rarely, seldom, no sooner',       mark: 'V',  lessons: 3 },
  { id: 'wishes',       n: '09', title: 'Wishes & Regrets',  subtitle: 'I wish, if only, I\'d rather',    mark: 'W',  lessons: 2 },
  { id: 'reported',     n: '10', title: 'Reported Speech',   subtitle: 'He said that…',                   mark: 'R',  lessons: 2 },
  { id: 'gerund',       n: '11', title: 'Gerund / Infinitive', subtitle: '-ing or to-',                   mark: 'G',  lessons: 2 },
  { id: 'causative',    n: '12', title: 'Causative',         subtitle: 'Have something done',             mark: 'H',  lessons: 2 },
  { id: 'phrasal-get',  n: '13', title: 'Phrasal: Get',      subtitle: 'Get it across, get rid of',       mark: 'P',  lessons: 2 },
  { id: 'tenses',       n: '14', title: 'Tenses',            subtitle: 'Perfect, continuous, simple',     mark: 'T',  lessons: 2 },
  { id: 'vocab-people', n: '15', title: 'People & Character',subtitle: 'Doer, dabbler, shopaholic',       mark: 'Y',  lessons: 2 },
  { id: 'vocab-time',   n: '16', title: 'Time & Life',       subtitle: 'Full diary, hectic, wrap up',     mark: 'D',  lessons: 2 },
  { id: 'dining',       n: '17', title: 'Dinner\u2019s on Me', subtitle: 'Entertaining & eating out',     mark: 'M',  lessons: 4 },
  { id: 'feelings',     n: '18', title: 'Feelings',           subtitle: 'Feel free, mixed feelings, no hard…', mark: 'S', lessons: 3 },
];

// Exercise types: 'choice' | 'gap' | 'bank' | 'type' | 'match'

const LESSONS = {
  // ── IDIOMS ─────────────────────────────────────────────────
  'idioms-1': {
    topicId: 'idioms', title: 'Everyday idioms', exercises: [
      { type:'choice', prompt:'Choose the idiom that means "accidentally reveal a secret".',
        options:['let the cat out of the bag','hit the nail on the head','bite the bullet','break the ice'],
        answer:'let the cat out of the bag' },
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'We were ___ in work when the power went out.',
        options:['up to our ears','on thin ice','in hot water','out of the blue'], answer:'up to our ears',
        hint:'very busy / overwhelmed' },
      { type:'match', prompt:'Match each idiom with its meaning.',
        pairs:[
          ['once in a blue moon','very rarely'],
          ['cost an arm and a leg','very expensive'],
          ['piece of cake','very easy'],
          ['under the weather','feeling ill'],
        ]},
      { type:'bank', prompt:'Build the sentence.',
        answer:'She really put her foot in it',
        bank:['She','really','put','her','foot','in','it','on','hand'],
        meaning:'to say something tactless or embarrassing' },
      { type:'type', prompt:'Complete: "He hit the nail on the ___"', answer:'head',
        hint:'to describe something exactly right' },
      { type:'choice', prompt:'"To bite the bullet" means…',
        options:['to face a difficult situation bravely','to make a hasty decision','to speak too quickly','to refuse to help'],
        answer:'to face a difficult situation bravely' },
      { type:'type', prompt:'Complete: "Let\'s break the ___" (= start a conversation)', answer:'ice' },
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'I\'ll have to ___ the bullet and tell him the truth.',
        options:['bite','chew','catch','take'], answer:'bite' },
    ]
  },
  'idioms-2': {
    topicId: 'idioms', title: 'Body & action idioms', exercises: [
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'I can\'t put my ___ on what\'s wrong.',
        options:['finger','hand','head','eye'], answer:'finger', hint:'to identify exactly' },
      { type:'match', prompt:'Match the body idioms.',
        pairs:[
          ['keep an eye on','watch carefully'],
          ['pull someone\'s leg','joke with them'],
          ['get cold feet','lose courage'],
          ['cost an arm and a leg','very expensive'],
        ]},
      { type:'bank', prompt:'Build the sentence.',
        answer:'I would give my right arm for it',
        bank:['I','would','give','my','right','arm','for','it','foot','hand'] },
      { type:'type', prompt:'Complete: "Let\'s call it a ___" (= stop work)', answer:'day' },
      { type:'choice', prompt:'"A blessing in disguise" means…',
        options:['a good thing that seemed bad at first','an unlucky event','a secret gift','a disguise'],
        answer:'a good thing that seemed bad at first' },
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'He got cold ___ at the last minute and refused to sign.',
        options:['feet','hands','eyes','head'], answer:'feet' },
      { type:'type', prompt:'Complete: "Stop pulling my ___" (= stop joking)', answer:'leg' },
      { type:'choice', prompt:'"To keep an eye on" means…',
        options:['to watch carefully','to look away','to close the eyes','to fix'],
        answer:'to watch carefully' },
    ]
  },
  'idioms-3': {
    topicId: 'idioms', title: 'Idioms in context', exercises: [
      { type:'choice', prompt:'"The ball is in your court" means…',
        options:['it\'s your turn to act','you are winning','you have been challenged','you are being tested'],
        answer:'it\'s your turn to act' },
      { type:'gap', prompt:'Fill in the idiom.',
        sentence:'Stop beating around the ___ and tell me the truth.',
        options:['bush','corner','tree','fence'], answer:'bush', hint:'avoiding the main point' },
      { type:'type', prompt:'"When pigs ___" — express that something will never happen.', answer:'fly' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'It is raining cats and dogs',
        bank:['It','is','raining','cats','and','dogs','mice','or'] },
      { type:'match', prompt:'Match each idiom with its meaning.',
        pairs:[
          ['on cloud nine','extremely happy'],
          ['over the moon','delighted'],
          ['down in the dumps','sad, depressed'],
          ['in seventh heaven','blissfully happy'],
        ]},
      { type:'choice', prompt:'"A storm in a teacup" means…',
        options:['a lot of fuss about nothing','a real emergency','a British habit','a quiet day'],
        answer:'a lot of fuss about nothing' },
      { type:'type', prompt:'Complete: "It\'s a piece of ___" (= very easy)', answer:'cake' },
    ]
  },
  'idioms-4': {
    topicId: 'idioms', title: 'Tricky idioms', exercises: [
      { type:'match', prompt:'Match the idioms.',
        pairs:[
          ['jump on the bandwagon','join a trend'],
          ['spill the beans','reveal a secret'],
          ['miss the boat','miss an opportunity'],
          ['hit the sack','go to bed'],
        ]},
      { type:'choice', prompt:'"To throw in the towel" means…',
        options:['to give up','to help someone','to clean up','to surrender playfully'],
        answer:'to give up' },
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'He always plays devil\'s ___ just to annoy us.',
        options:['advocate','son','friend','voice'], answer:'advocate' },
      { type:'type', prompt:'Complete: "It costs an arm and a ___"', answer:'leg' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'Don\'t judge a book by its cover',
        bank:['Don\'t','judge','a','book','by','its','cover','the','on'] },
      { type:'choice', prompt:'"The last straw" means…',
        options:['the final small thing that makes one give up','a great finale','the best moment','the first problem'],
        answer:'the final small thing that makes one give up' },
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'We should cross that ___ when we come to it.',
        options:['bridge','road','street','line'], answer:'bridge' },
    ]
  },

  // ── USING LANGUAGE ──
  'language-1': {
    topicId: 'language', title: 'Communication problems', exercises: [
      { type:'choice', prompt:'"To talk at cross-purposes" means…',
        options:['to misunderstand each other','to argue angrily','to whisper','to speak formally'],
        answer:'to misunderstand each other' },
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'She can\'t ___ a word in edgeways when her brother is speaking.',
        options:['get','say','put','make'], answer:'get', hint:'interrupt to speak' },
      { type:'type', prompt:'Complete: "He\'s got the wrong end of the ___" (misunderstood)', answer:'stick' },
      { type:'match', prompt:'Match the expressions.',
        pairs:[
          ['make head or tail of','understand'],
          ['cross-purposes','mutual misunderstanding'],
          ['wrong end of the stick','misunderstand'],
          ['get a word in edgeways','find a moment to speak'],
        ]},
      { type:'bank', prompt:'Build the sentence.',
        answer:'I cannot make head or tail of this',
        bank:['I','cannot','make','head','or','tail','of','this','and','foot'] },
      { type:'choice', prompt:'"Beat around the bush" means…',
        options:['avoid getting to the point','speak loudly','hit a plant','criticise someone'],
        answer:'avoid getting to the point' },
      { type:'gap', prompt:'Fill the gap.',
        sentence:'Could you put it in a ___? I don\'t have much time.',
        options:['nutshell','second','letter','page'], answer:'nutshell' },
    ]
  },
  'language-2': {
    topicId: 'language', title: 'Good talk, bad talk', exercises: [
      { type:'match', prompt:'Match the "talk" expressions.',
        pairs:[
          ['talk down to','speak as if inferior'],
          ['talk behind back','say negative things when absent'],
          ['small talk','social, light talk'],
          ['talk shop','talk about work'],
        ]},
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'My colleagues always ___ shop over lunch, and it bores me rigid.',
        options:['talk','speak','say','tell'], answer:'talk' },
      { type:'choice', prompt:'"To give someone a talking to" means…',
        options:['to scold/reproach them','to have a long chat','to introduce them','to whisper'],
        answer:'to scold/reproach them' },
      { type:'type', prompt:'Complete: "Your friend is a real talking-___ among the staff"', answer:'point',
        hint:'subject everyone wants to talk about' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'It was just small talk nothing more',
        bank:['It','was','just','small','talk','nothing','more','big','less'] },
      { type:'choice', prompt:'Someone "long-winded" is…',
        options:['talks too much with little point','very concise','windy outdoors','a fast speaker'],
        answer:'talks too much with little point' },
      { type:'gap', prompt:'Complete the expression.',
        sentence:'Stop talking ___ and listen to me!',
        options:['rubbish','shop','back','down'], answer:'rubbish' },
    ]
  },
  'language-3': {
    topicId: 'language', title: 'Meetings & discussions', exercises: [
      { type:'match', prompt:'Match phrases with their meaning.',
        pairs:[
          ['start the ball rolling','begin the discussion'],
          ['put it in a nutshell','say it briefly'],
          ['speak my mind','say what I truly think'],
          ['wrap up','finish / conclude'],
        ]},
      { type:'choice', prompt:'"Long-winded" describes someone who…',
        options:['talks too much with little point','whispers','lies often','never speaks'],
        answer:'talks too much with little point' },
      { type:'gap', prompt:'Complete the expression.',
        sentence:'Iris always talks ___ — no sense, just nonsense.',
        options:['rubbish','sense','shop','back'], answer:'rubbish' },
      { type:'type', prompt:'Complete: "Who\'s going to start the ball ___?"', answer:'rolling' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'I hope we wrap up the discussion by twelve',
        bank:['I','hope','we','wrap','up','the','discussion','by','twelve','down','in'] },
      { type:'choice', prompt:'"To speak one\'s mind" means…',
        options:['to say what you really think','to remain silent','to read minds','to speak publicly'],
        answer:'to say what you really think' },
      { type:'type', prompt:'Complete: "Let me put it in a ___" (= briefly)', answer:'nutshell' },
    ]
  },

  // ── EMPHASISING ──
  'emphasising-1': {
    topicId: 'emphasising', title: 'Emphatic adjectives', exercises: [
      { type:'match', prompt:'Match each phrase with what it emphasises.',
        pairs:[
          ['bone dry','completely dry'],
          ['rock hard','extremely hard'],
          ['stone cold','very cold'],
          ['piping hot','very hot'],
        ]},
      { type:'gap', prompt:'Complete the phrase.',
        sentence:'Our dinner was ___ cold instead of piping hot.',
        options:['stone','bone','rock','stark'], answer:'stone' },
      { type:'choice', prompt:'"Crystal clear" means…',
        options:['completely clear / obvious','slightly unclear','made of crystal','very bright'],
        answer:'completely clear / obvious' },
      { type:'type', prompt:'Complete: "Grandad is 87 but he\'s ___ fit"', answer:'fighting',
        hint:'extremely fit' },
      { type:'match', prompt:'Match more phrases.',
        pairs:[
          ['razor-sharp','very sharp (mind/wit)'],
          ['squeaky-clean','spotless / scandal-free'],
          ['stark naked','completely naked'],
          ['filthy rich','extremely wealthy'],
        ]},
      { type:'bank', prompt:'Build the sentence.',
        answer:'His uncle is filthy rich',
        bank:['His','uncle','is','filthy','rich','poor','dirty','hand'] },
      { type:'gap', prompt:'Fill the gap.',
        sentence:'The car was ___ new, not a scratch on it.',
        options:['brand','fresh','shop','pure'], answer:'brand' },
      { type:'type', prompt:'Complete: "The water was ___ cold" (extremely)', answer:'ice' },
    ]
  },
  'emphasising-2': {
    topicId: 'emphasising', title: 'Emphatic noun phrases', exercises: [
      { type:'match', prompt:'Match each phrase with its meaning.',
        pairs:[
          ['in broad daylight','during the day when visible'],
          ['rock bottom','the lowest point'],
          ['a small fortune','a large sum of money'],
          ['a mere pittance','a very small amount'],
        ]},
      { type:'choice', prompt:'"Bare-faced lies" are…',
        options:['obvious, shameless untruths','white lies','polite lies','unintentional mistakes'],
        answer:'obvious, shameless untruths' },
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'The city spent a small ___ on surveillance cameras.',
        options:['fortune','money','sum','amount'], answer:'fortune' },
      { type:'type', prompt:'Complete: "full ___" — there is nothing more to say', answer:'stop' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'She was robbed in broad daylight',
        bank:['She','was','robbed','in','broad','daylight','night','wide','hand'] },
      { type:'gap', prompt:'Fill the gap.',
        sentence:'After the divorce, he hit rock ___.',
        options:['bottom','down','deep','low'], answer:'bottom' },
      { type:'type', prompt:'Complete: "a mere ___" — a trivial amount', answer:'pittance' },
    ]
  },
  'emphasising-3': {
    topicId: 'emphasising', title: 'Absolutely / utterly', exercises: [
      { type:'match', prompt:'Match the intensifier with a typical adjective.',
        pairs:[
          ['absolutely','terrified'],
          ['utterly','exhausted'],
          ['completely','wrong'],
          ['totally','obsessed'],
        ]},
      { type:'choice', prompt:'Which is incorrect?',
        options:['very terrified','absolutely terrified','completely terrified','utterly terrified'],
        answer:'very terrified' },
      { type:'gap', prompt:'Complete with the strongest form.',
        sentence:'I was ___ exhausted after the hike.',
        options:['utterly','quite','slightly','a bit'], answer:'utterly' },
      { type:'type', prompt:'Complete: "absolutely f___" (extremely tired)', answer:'furious',
        hint:'a gradable → ungradable partner: "very angry" becomes "absolutely furious"' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'The film was absolutely fantastic',
        bank:['The','film','was','absolutely','fantastic','very','really','good'] },
    ]
  },

  // ── OPPOSITES ──
  'opposites-1': {
    topicId: 'opposites', title: 'Choosing the right prefix', exercises: [
      { type:'choice', prompt:'Which prefix makes the opposite of "legal"?',
        options:['il-','un-','in-','dis-'], answer:'il-' },
      { type:'choice', prompt:'Opposite of "responsible"?',
        options:['irresponsible','unresponsible','disresponsible','inresponsible'],
        answer:'irresponsible' },
      { type:'type', prompt:'Opposite of "mature" — add the correct prefix.', answer:'immature' },
      { type:'type', prompt:'Opposite of "honest" — add the correct prefix.', answer:'dishonest' },
      { type:'match', prompt:'Match the word with its opposite prefix.',
        pairs:[
          ['accurate','in-'],
          ['believable','un-'],
          ['legal','il-'],
          ['relevant','ir-'],
        ]},
      { type:'gap', prompt:'Fill the correct prefix.',
        sentence:'Your behaviour was completely ___responsible! You\'re not eight!',
        options:['ir','un','im','dis'], answer:'ir' },
      { type:'type', prompt:'Opposite of "logical"?', answer:'illogical' },
      { type:'type', prompt:'Opposite of "possible"?', answer:'impossible' },
    ]
  },
  'opposites-2': {
    topicId: 'opposites', title: 'Prefixes in context', exercises: [
      { type:'gap', prompt:'Fill the correct prefix.',
        sentence:'Don\'t be so ___patient! I\'ll help you in a minute.',
        options:['im','in','un','dis'], answer:'im' },
      { type:'gap', prompt:'Fill the correct prefix.',
        sentence:'I\'m afraid your answer is ___correct. Try again.',
        options:['in','un','im','ir'], answer:'in' },
      { type:'gap', prompt:'Fill the correct prefix.',
        sentence:'She\'s completely ___literate — never learnt to read.',
        options:['il','un','in','im'], answer:'il' },
      { type:'choice', prompt:'Which is INCORRECT?',
        options:['unmoral','immoral','immortal','impatient'],
        answer:'unmoral' },
      { type:'type', prompt:'Opposite of "perfect"?', answer:'imperfect' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'He is very disagreeable when tired',
        bank:['He','is','very','disagreeable','when','tired','agreeable','unagreeable'] },
      { type:'gap', prompt:'Fill the correct prefix.',
        sentence:'That comment was totally ___appropriate at a wedding.',
        options:['in','un','im','dis'], answer:'in' },
      { type:'type', prompt:'Opposite of "agree"?', answer:'disagree' },
    ]
  },
  'opposites-3': {
    topicId: 'opposites', title: '-ful → -less exceptions', exercises: [
      { type:'type', prompt:'Opposite of "thoughtful" (ends in -ful rule)', answer:'thoughtless' },
      { type:'type', prompt:'Opposite of "useful" (ends in -ful rule)', answer:'useless' },
      { type:'choice', prompt:'Which follows the -ful → -less rule?',
        options:['hopeful → hopeless','hopeful → unhopeful','hopeful → dishopeful','hopeful → inhopeful'],
        answer:'hopeful → hopeless' },
      { type:'match', prompt:'Match each word to its opposite.',
        pairs:[
          ['careful','careless'],
          ['painful','painless'],
          ['harmful','harmless'],
          ['helpful','helpless'],
        ]},
      { type:'gap', prompt:'Fill in the blank.',
        sentence:'The injection is completely ___, don\'t worry.',
        options:['painless','painful','unpainful','inpain'], answer:'painless' },
      { type:'type', prompt:'Opposite of "tactful"', answer:'tactless' },
      { type:'choice', prompt:'Which exception does NOT follow -ful/-less?',
        options:['beautiful','careful','painful','useful'],
        answer:'beautiful', hint:'"beautiful" has no -less opposite; use "ugly"' },
    ]
  },

  // ── FREE TIME & LEISURE ──
  'freetime-1': {
    topicId: 'freetime', title: 'Adjectives for pursuits', exercises: [
      { type:'match', prompt:'Match each adjective with its meaning.',
        pairs:[
          ['rewarding','gives positive experiences'],
          ['fruitful','produces good results'],
          ['lucrative','makes a lot of money'],
          ['therapeutic','healthy for body/mind'],
        ]},
      { type:'gap', prompt:'Complete the sentence.',
        sentence:'Painting is such a ___ activity — it calms me down.',
        options:['therapeutic','lucrative','time-consuming','fruitful'], answer:'therapeutic' },
      { type:'choice', prompt:'"Time-consuming" means…',
        options:['takes a long time to do','saves time','is enjoyable','is efficient'],
        answer:'takes a long time to do' },
      { type:'type', prompt:'"Selling my own crafts has become a ___ hobby." (makes money)', answer:'lucrative' },
      { type:'gap', prompt:'Complete the sentence.',
        sentence:'The volunteer work was incredibly ___ — I felt useful.',
        options:['rewarding','lucrative','time-consuming','fruitless'], answer:'rewarding' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'Reading is very relaxing and calming',
        bank:['Reading','is','very','relaxing','and','calming','rewarding','hectic'] },
      { type:'choice', prompt:'A "fruitful" discussion is one that…',
        options:['produces good results','tastes sweet','takes too long','goes in circles'],
        answer:'produces good results' },
    ]
  },
  'freetime-2': {
    topicId: 'freetime', title: 'How people spend leisure', exercises: [
      { type:'match', prompt:'Match each informal word with its meaning.',
        pairs:[
          ['culture vulture','big fan of anything cultural'],
          ['couch potato','physically inactive person'],
          ['dabbler','never sticks to one activity'],
          ['doer','believes in action, not thinking'],
        ]},
      { type:'choice', prompt:'A "shopaholic" is someone who…',
        options:['is addicted to shopping','runs a shop','hates shops','shops only once a year'],
        answer:'is addicted to shopping' },
      { type:'gap', prompt:'Complete.',
        sentence:'Bob\'s a real culture ___ — he\'s at every gallery opening.',
        options:['vulture','hawk','pigeon','bird'], answer:'vulture' },
      { type:'gap', prompt:'Complete.',
        sentence:'Stop being such a couch ___ and come for a walk!',
        options:['potato','tomato','carrot','pillow'], answer:'potato' },
      { type:'type', prompt:'Someone who tries pastimes briefly and drops them is a ___', answer:'dabbler' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'Francis is a real doer not a dreamer',
        bank:['Francis','is','a','real','doer','not','a','dreamer','hand','the'] },
      { type:'choice', prompt:'Which word fits: "Laura buys things she doesn\'t need — she\'s a ___"',
        options:['shopaholic','culture vulture','couch potato','doer'],
        answer:'shopaholic' },
    ]
  },
  'freetime-3': {
    topicId: 'freetime', title: 'Involvement in activities', exercises: [
      { type:'match', prompt:'Match each expression with its informal meaning.',
        pairs:[
          ['heavily into','very interested in'],
          ['hooked on','addicted to (positively)'],
          ['went off','lost interest in'],
          ['get up to','do (at weekends etc.)'],
        ]},
      { type:'gap', prompt:'Complete the expression.',
        sentence:'Joe is heavily ___ downhill skiing these days.',
        options:['into','on','up','at'], answer:'into' },
      { type:'gap', prompt:'Complete the expression.',
        sentence:'He\'s totally ___ on motor racing — watches every weekend.',
        options:['hooked','stuck','locked','pulled'], answer:'hooked' },
      { type:'choice', prompt:'"I went off football and started golf" means…',
        options:['I lost interest in football','I travelled to watch football','I dislike golf','I quit both'],
        answer:'I lost interest in football' },
      { type:'type', prompt:'Complete: "What do you ___ ___ at weekends?" (informal: do)', answer:'get up' },
      { type:'gap', prompt:'Complete.',
        sentence:'She has a pretty full ___ — no free evenings this week.',
        options:['diary','book','paper','list'], answer:'diary' },
      { type:'choice', prompt:'"She locks herself away" means…',
        options:['she isolates herself','she forgets her keys','she runs away','she hides an object'],
        answer:'she isolates herself' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'I have a pretty hectic social life',
        bank:['I','have','a','pretty','hectic','social','life','full','small'] },
    ]
  },

  // ── COLOUR ──
  'colours-1': {
    topicId: 'colours', title: 'Specific colours & shades', exercises: [
      { type:'match', prompt:'Match each colour word with what it describes.',
        pairs:[
          ['auburn','red-brown hair'],
          ['chestnut','deep reddish brown'],
          ['mousy','dull light brown (hair)'],
          ['ginger','orangey red (hair/cats)'],
        ]},
      { type:'choice', prompt:'"Scarlet" is…',
        options:['a brilliant red','a deep blue','a pale pink','a dark green'],
        answer:'a brilliant red' },
      { type:'choice', prompt:'"Crimson" means…',
        options:['strong deep red','light pink','bright orange','pale blue'],
        answer:'strong deep red' },
      { type:'gap', prompt:'Complete.',
        sentence:'He wore a ___ blue suit to the wedding — very dark.',
        options:['navy','turquoise','shocking','auburn'], answer:'navy' },
      { type:'type', prompt:'An extremely bright pink is called ___ pink.', answer:'shocking' },
      { type:'match', prompt:'Match the black/red words with meaning.',
        pairs:[
          ['jet black','intensely black (hair, eyes)'],
          ['pitch black','intensely black (darkness)'],
          ['scarlet','brilliant red'],
          ['crimson','strong deep red'],
        ]},
      { type:'gap', prompt:'Complete.',
        sentence:'The sea was a beautiful ___ — greenish blue.',
        options:['turquoise','navy','ginger','mousy'], answer:'turquoise' },
      { type:'choice', prompt:'"Beige" is…',
        options:['a light creamy brown','a bright green','a deep black','a warm red'],
        answer:'a light creamy brown' },
    ]
  },
  'colours-2': {
    topicId: 'colours', title: 'Talking about colour', exercises: [
      { type:'match', prompt:'Match each word with its meaning.',
        pairs:[
          ['primary colour','red, blue or yellow'],
          ['pastel','pale shade of a colour'],
          ['vivid','strong, bright (like scarlet)'],
          ['fluorescent','glowing bright colours'],
        ]},
      { type:'choice', prompt:'"Electric blue" means…',
        options:['extremely bright / glowing blue','pale blue','navy blue','a blue power cord'],
        answer:'extremely bright / glowing blue' },
      { type:'gap', prompt:'Complete the sentence.',
        sentence:'There\'s a slight ___ of green in the paint.',
        options:['tinge','ray','splash','drop'], answer:'tinge',
        hint:'a small shade / trace' },
      { type:'type', prompt:'A photo that uses only one colour is called m___.', answer:'monochrome' },
      { type:'choice', prompt:'The suffixes -y and -ish show that a colour is…',
        options:['partly present','fully saturated','very bright','darker'],
        answer:'partly present' },
      { type:'gap', prompt:'Complete.',
        sentence:'Her dress was a soft ___ yellow — very pale.',
        options:['pale','vivid','fluorescent','jet'], answer:'pale' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'The walls were a bluey green colour',
        bank:['The','walls','were','a','bluey','green','colour','blue','gray','a'] },
    ]
  },
  'colours-3': {
    topicId: 'colours', title: 'Colour metaphors', exercises: [
      { type:'match', prompt:'Match colour metaphor with meaning.',
        pairs:[
          ['feel blue','feel depressed'],
          ['see red','be very angry'],
          ['turn green','feel nauseous / envious'],
          ['look green','look ill / pale sickly'],
        ]},
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'When Bill saw my new car he was ___ with envy.',
        options:['green','red','blue','yellow'], answer:'green' },
      { type:'gap', prompt:'Complete the idiom.',
        sentence:'Tina comes here once in a ___ moon.',
        options:['blue','red','green','white'], answer:'blue' },
      { type:'type', prompt:'Complete: "The visitors were given the ___ carpet treatment." (special)', answer:'red' },
      { type:'choice', prompt:'"Out of the blue" means…',
        options:['unexpectedly','from the sky','rarely','sadly'], answer:'unexpectedly' },
      { type:'match', prompt:'Match more metaphors.',
        pairs:[
          ['black sheep','the odd / bad one out'],
          ['black market','illegal trade'],
          ['a black mark','a negative record'],
          ['a black future','without hope'],
        ]},
      { type:'gap', prompt:'Complete.',
        sentence:'My brother left home at 17 — he was the ___ sheep of the family.',
        options:['black','white','grey','red'], answer:'black' },
      { type:'choice', prompt:'"A red-letter day" is…',
        options:['an important / special day','a sad day','a busy work day','a rainy day'],
        answer:'an important / special day' },
    ]
  },
  'colours-4': {
    topicId: 'colours', title: 'Grey, white & workers', exercises: [
      { type:'match', prompt:'Match the phrase with its meaning.',
        pairs:[
          ['grey area','unclear situation'],
          ['grey matter','brains / intellect'],
          ['grey cells','the brain'],
          ['white as a sheet','pale with fear'],
        ]},
      { type:'choice', prompt:'"White-collar workers" are…',
        options:['office workers','manual workers','medical staff','young workers'],
        answer:'office workers' },
      { type:'choice', prompt:'"Blue-collar workers" are…',
        options:['manual / physical workers','office workers','police','students'],
        answer:'manual / physical workers' },
      { type:'gap', prompt:'Complete.',
        sentence:'Use your ___ cells — think about it!',
        options:['grey','white','blue','red'], answer:'grey' },
      { type:'type', prompt:'A terrifying ride is a "white ___ ride".', answer:'knuckle' },
      { type:'gap', prompt:'Complete.',
        sentence:'She saw a spider and went ___ as a sheet.',
        options:['white','black','red','green'], answer:'white' },
      { type:'match', prompt:'Match the "paint/red" phrases.',
        pairs:[
          ['paint the town red','go out and celebrate'],
          ['in the red','in debt'],
          ['red alert','state of danger'],
          ['see red','be very angry'],
        ]},
      { type:'choice', prompt:'"A red-point of view" refers to…',
        options:['left-wing politics','danger warning','a special occasion','anger'],
        answer:'left-wing politics' },
      { type:'type', prompt:'Complete: "as black as ___" (= very angry)', answer:'thunder' },
    ]
  },

  // ── CONDITIONALS ──
  'conditionals-1': {
    topicId: 'conditionals', title: 'Zero & first', exercises: [
      { type:'choice', prompt:'Pick the zero conditional.',
        options:['If you heat ice, it melts.','If I had time, I would help.','If it rains, I\'ll stay home.','If I were rich, I\'d travel.'],
        answer:'If you heat ice, it melts.' },
      { type:'gap', prompt:'First conditional.',
        sentence:'If it ___ tomorrow, we\'ll cancel the picnic.',
        options:['rains','rained','will rain','would rain'], answer:'rains' },
      { type:'bank', prompt:'Build a first conditional.',
        answer:'If I see her I will tell her',
        bank:['If','I','see','her','I','will','tell','her','saw','would','a'] },
      { type:'type', prompt:'Complete: "If you ___ (press) this, the lights turn on."', answer:'press' },
      { type:'gap', prompt:'First conditional.',
        sentence:'If you ___ me, I\'ll come over immediately.',
        options:['call','called','will call','would call'], answer:'call' },
      { type:'choice', prompt:'Which is zero conditional?',
        options:['If you heat water, it boils.','If I won, I\'d buy a car.','Had I known, I\'d have left.','If it rains, I\'ll stay.'],
        answer:'If you heat water, it boils.' },
    ]
  },
  'conditionals-2': {
    topicId: 'conditionals', title: 'Second conditional', exercises: [
      { type:'choice', prompt:'Pick the second conditional.',
        options:['If I had more time, I would travel.','If it rains, I\'ll stay.','If you heat water, it boils.','If I had known, I would have gone.'],
        answer:'If I had more time, I would travel.' },
      { type:'gap', prompt:'Second conditional.',
        sentence:'If I ___ you, I would take the job.',
        options:['were','was','am','be'], answer:'were' },
      { type:'bank', prompt:'Build a second conditional.',
        answer:'If I had a car I would drive',
        bank:['If','I','had','a','car','I','would','drive','have','will'] },
      { type:'type', prompt:'Complete: "If I ___ (win) the lottery, I\'d buy a house."', answer:'won' },
      { type:'gap', prompt:'Complete.',
        sentence:'If she ___ harder, she would pass the exam.',
        options:['studied','studies','would study','had studied'], answer:'studied' },
      { type:'choice', prompt:'Correct form?',
        options:['If I had a million, I would travel.','If I have a million, I travel.','If I had a million, I will travel.','If I had a million, I travelled.'],
        answer:'If I had a million, I would travel.' },
    ]
  },
  'conditionals-3': {
    topicId: 'conditionals', title: 'Third & mixed', exercises: [
      { type:'choice', prompt:'Pick the third conditional.',
        options:['If I had studied, I would have passed.','If I were taller, I\'d reach it.','If you heat ice, it melts.','If I find my keys, I\'ll call you.'],
        answer:'If I had studied, I would have passed.' },
      { type:'gap', prompt:'Third conditional.',
        sentence:'If I ___ earlier, I would have caught the train.',
        options:['had left','left','would leave','leave'], answer:'had left' },
      { type:'gap', prompt:'Mixed conditional.',
        sentence:'If I had taken the job, I ___ living in Berlin now.',
        options:['would be','would have been','was','will be'], answer:'would be' },
      { type:'bank', prompt:'Build a third conditional.',
        answer:'If we had known we would have come',
        bank:['If','we','had','known','we','would','have','come','will','know'] },
      { type:'type', prompt:'Complete: "If she ___ (study), she would have passed."', answer:'had studied' },
      { type:'choice', prompt:'Which is mixed?',
        options:['If I had slept, I wouldn\'t be tired now.','If I sleep, I\'ll feel better.','If I had slept, I would have rested.','If I slept, I\'d feel better.'],
        answer:'If I had slept, I wouldn\'t be tired now.' },
    ]
  },

  // ── INVERSIONS ──
  'inversions-1': {
    topicId: 'inversions', title: 'Negative adverbials', exercises: [
      { type:'choice', prompt:'Pick the correctly inverted sentence.',
        options:['Never have I seen such beauty.','Never I have seen such beauty.','Never saw I such beauty.','Never I saw such beauty.'],
        answer:'Never have I seen such beauty.' },
      { type:'gap', prompt:'Complete the inversion.',
        sentence:'Rarely ___ such a brave man.',
        options:['have I met','I have met','I did meet','do I meet'], answer:'have I met' },
      { type:'bank', prompt:'Build the inversion.',
        answer:'Seldom do I eat fast food',
        bank:['Seldom','do','I','eat','fast','food','did','have','a'] },
      { type:'type', prompt:'Complete: "___ had I sat down when the phone rang." (barely)',
        answer:'Hardly', hint:'"Hardly had I… when…"' },
      { type:'match', prompt:'Match adverbial with meaning.',
        pairs:[
          ['rarely','not often'],
          ['seldom','not often'],
          ['hardly','almost not'],
          ['no sooner','immediately after'],
        ]},
      { type:'gap', prompt:'Complete.',
        sentence:'No sooner ___ sat down than the bell rang.',
        options:['had I','I had','did I','I did'], answer:'had I' },
    ]
  },
  'inversions-2': {
    topicId: 'inversions', title: 'Conditional without if', exercises: [
      { type:'choice', prompt:'Which is a correct inverted conditional?',
        options:['Had I known, I would have stayed.','Would I have known, I had stayed.','Knew I, I would have stayed.','If had I known, I\'d stayed.'],
        answer:'Had I known, I would have stayed.' },
      { type:'gap', prompt:'Complete without "if".',
        sentence:'___ you hear anything, let me know.',
        options:['Should','If','Were','Had'], answer:'Should' },
      { type:'bank', prompt:'Build the inversion.',
        answer:'Were they to escape there would be an outcry',
        bank:['Were','they','to','escape','there','would','be','an','outcry','was','will'] },
      { type:'type', prompt:'Rewrite without "if": "If she had come, she would have met him."',
        answer:'Had she come, she would have met him',
        hint:'Start with "Had"' },
      { type:'choice', prompt:'Which matches "If I were rich"?',
        options:['Were I rich','Had I rich','Should I rich','Would I rich'],
        answer:'Were I rich' },
    ]
  },
  'inversions-3': {
    topicId: 'inversions', title: 'After only & so/such', exercises: [
      { type:'choice', prompt:'Which is correct?',
        options:['So devastating were the floods that some areas never recover.','So devastating the floods were that some areas never recover.','So devastating was the floods that some areas never recover.','So devastating the floods were.'],
        answer:'So devastating were the floods that some areas never recover.' },
      { type:'gap', prompt:'Complete.',
        sentence:'Only after posting the letter ___ I had forgotten the stamp.',
        options:['did I remember','I remembered','I did remember','had I remembered'], answer:'did I remember' },
      { type:'bank', prompt:'Build the inversion.',
        answer:'Not only did he fail he also lied',
        bank:['Not','only','did','he','fail','he','also','lied','was','does','has'] },
      { type:'type', prompt:'Complete: "So ___ was his speech that everyone cried." (moving)', answer:'moving' },
      { type:'gap', prompt:'Complete.',
        sentence:'Such ___ the crowd that the police had to intervene.',
        options:['was','were','did','had'], answer:'was' },
    ]
  },

  // ── WISHES & REGRETS ──
  'wishes-1': {
    topicId: 'wishes', title: 'I wish / if only', exercises: [
      { type:'choice', prompt:'Pick the correct regret about the past.',
        options:['I wish I had studied harder.','I wish I studied harder.','I wish I would study harder.','I wish I study harder.'],
        answer:'I wish I had studied harder.' },
      { type:'gap', prompt:'Complete.',
        sentence:'I wish I ___ what to say.',
        options:['knew','know','had known','would know'], answer:'knew' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'If only I had listened to her',
        bank:['If','only','I','had','listened','to','her','have','listen'] },
      { type:'type', prompt:'Complete: "I wish it ___ (stop) raining."', answer:'would stop' },
      { type:'choice', prompt:'"I wish I were taller" expresses…',
        options:['a present regret/wish','a past regret','a future plan','an order'],
        answer:'a present regret/wish' },
      { type:'gap', prompt:'Complete.',
        sentence:'I wish you ___ smoking in the house.',
        options:['wouldn\'t','don\'t','didn\'t','aren\'t'], answer:'wouldn\'t' },
    ]
  },
  'wishes-2': {
    topicId: 'wishes', title: 'Would rather / it\'s time', exercises: [
      { type:'choice', prompt:'Which is correct?',
        options:['I\'d rather you didn\'t smoke here.','I\'d rather you don\'t smoke here.','I\'d rather you smoke not here.','I\'d rather not you smoke here.'],
        answer:'I\'d rather you didn\'t smoke here.' },
      { type:'gap', prompt:'Complete.',
        sentence:'It\'s time you ___ a decision.',
        options:['made','make','had made','making'], answer:'made' },
      { type:'type', prompt:'Complete: "I\'d rather you ___ (tell) me the truth yesterday."', answer:'had told' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'It is high time we went home',
        bank:['It','is','high','time','we','went','home','go','going','a'] },
      { type:'choice', prompt:'"I\'d rather + past simple" expresses…',
        options:['preference about someone else','past action','future plan','regret'],
        answer:'preference about someone else' },
    ]
  },

  // ── REPORTED SPEECH ──
  'reported-1': {
    topicId: 'reported', title: 'Backshift', exercises: [
      { type:'choice', prompt:'Direct: "I am tired." Which is the reported version?',
        options:['He said he was tired.','He said he is tired.','He says he was tired.','He said he be tired.'],
        answer:'He said he was tired.' },
      { type:'gap', prompt:'Complete.',
        sentence:'She said she ___ finished the book.',
        options:['had','has','have','did'], answer:'had' },
      { type:'type', prompt:'Direct: "I will call you." → He said he ___ call me.', answer:'would' },
      { type:'bank', prompt:'Build the reported sentence.',
        answer:'She told me she had seen the film',
        bank:['She','told','me','she','had','seen','the','film','saw','have'] },
      { type:'gap', prompt:'Complete.',
        sentence:'They said they ___ tomorrow — they meant the next day.',
        options:['would come','will come','came','come'], answer:'would come' },
      { type:'choice', prompt:'"I can drive" becomes…',
        options:['He said he could drive.','He said he can drive.','He said he could drove.','He said he can drove.'],
        answer:'He said he could drive.' },
    ]
  },
  'reported-2': {
    topicId: 'reported', title: 'Questions & commands', exercises: [
      { type:'choice', prompt:'Direct: "Where do you live?" → Reported:',
        options:['He asked where I lived.','He asked where did I live.','He asked where do I live.','He asked I lived where.'],
        answer:'He asked where I lived.' },
      { type:'gap', prompt:'Complete the reported command.',
        sentence:'The teacher told us ___ quiet.',
        options:['to be','be','being','that we were'], answer:'to be' },
      { type:'type', prompt:'Direct: "Don\'t be late." → He told me ___ be late.', answer:'not to' },
      { type:'bank', prompt:'Build the reported question.',
        answer:'She asked me if I could help',
        bank:['She','asked','me','if','I','could','help','can','was','do'] },
      { type:'choice', prompt:'"Are you happy?" becomes…',
        options:['He asked if I was happy.','He asked was I happy.','He asked do I happy.','He asked if I happy.'],
        answer:'He asked if I was happy.' },
      { type:'gap', prompt:'Complete.',
        sentence:'He asked me ___ I had been.',
        options:['where','when','who','why'], answer:'where' },
    ]
  },

  // ── GERUND / INFINITIVE ──
  'gerund-1': {
    topicId: 'gerund', title: 'Gerund or infinitive?', exercises: [
      { type:'choice', prompt:'Pick the correct form.',
        options:['I enjoy swimming in the sea.','I enjoy to swim in the sea.','I enjoy swim in the sea.','I enjoy for swimming in the sea.'],
        answer:'I enjoy swimming in the sea.' },
      { type:'gap', prompt:'Fill in the correct form.',
        sentence:'She decided ___ the job.',
        options:['to take','taking','take','took'], answer:'to take' },
      { type:'type', prompt:'Complete: "He avoided ___ (meet) her."', answer:'meeting' },
      { type:'match', prompt:'Match verb with form it takes.',
        pairs:[
          ['enjoy','+ gerund'],
          ['decide','+ infinitive'],
          ['avoid','+ gerund'],
          ['promise','+ infinitive'],
        ]},
      { type:'gap', prompt:'Complete.',
        sentence:'I can\'t imagine ___ (live) without music.',
        options:['living','to live','live','lived'], answer:'living' },
      { type:'choice', prompt:'Which is correct?',
        options:['He refused to help us.','He refused helping us.','He refused help us.','He refused helped us.'],
        answer:'He refused to help us.' },
    ]
  },
  'gerund-2': {
    topicId: 'gerund', title: 'Change of meaning', exercises: [
      { type:'choice', prompt:'"I stopped smoking" means…',
        options:['I quit the habit.','I paused to smoke.','I began smoking.','I refused smoking.'],
        answer:'I quit the habit.' },
      { type:'choice', prompt:'"I stopped to smoke" means…',
        options:['I paused in order to smoke.','I quit the habit.','I thought about smoking.','I refused smoking.'],
        answer:'I paused in order to smoke.' },
      { type:'gap', prompt:'Remember + gerund = memory of the past.',
        sentence:'I remember ___ him at the party.',
        options:['meeting','to meet','met','meets'], answer:'meeting' },
      { type:'type', prompt:'Complete: "Don\'t forget ___ (lock) the door!"', answer:'to lock' },
      { type:'choice', prompt:'"Try + gerund" means…',
        options:['do something as an experiment','make an effort','refuse','begin'],
        answer:'do something as an experiment' },
      { type:'gap', prompt:'Complete.',
        sentence:'I regret ___ you, but the flight is cancelled.',
        options:['to tell','telling','tell','told'], answer:'to tell',
        hint:'regret + to-inf. = sorry to give bad news now' },
    ]
  },

  // ── CAUSATIVE ──
  'causative-1': {
    topicId: 'causative', title: 'Have / get something done', exercises: [
      { type:'choice', prompt:'Pick the correct causative form.',
        options:['I had my hair cut yesterday.','I had cut my hair yesterday.','I had my hair cutting yesterday.','I had cutted my hair yesterday.'],
        answer:'I had my hair cut yesterday.' },
      { type:'gap', prompt:'Complete the causative.',
        sentence:'We are ___ the house painted next week.',
        options:['having','doing','making','getting having'], answer:'having' },
      { type:'type', prompt:'Rewrite: "A painter painted our house." → We ___ our house painted.', answer:'had' },
      { type:'bank', prompt:'Build the causative.',
        answer:'I am having my hair cut this afternoon',
        bank:['I','am','having','my','hair','cut','this','afternoon','had','have','my'] },
      { type:'gap', prompt:'Complete.',
        sentence:'She got her nails ___ at the salon.',
        options:['done','do','doing','did'], answer:'done' },
      { type:'choice', prompt:'Which uses "get + done" correctly?',
        options:['I got my car serviced last week.','I got my car service last week.','I got to service my car.','I got servicing my car.'],
        answer:'I got my car serviced last week.' },
    ]
  },
  'causative-2': {
    topicId: 'causative', title: 'Causative in context', exercises: [
      { type:'type', prompt:'Rewrite: "Someone has stolen my bike." → I\'ve ___ my bike stolen.', answer:'had' },
      { type:'choice', prompt:'Which sentence uses the causative correctly?',
        options:['He had his nose broken in a fight.','He broke his nose in a fight had.','He had broken his nose fight.','He have his nose broken in a fight.'],
        answer:'He had his nose broken in a fight.' },
      { type:'gap', prompt:'Complete.',
        sentence:'Isn\'t it time you ___ your TV fixed?',
        options:['had','have','having','have had'], answer:'had' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'I will have my car serviced tomorrow',
        bank:['I','will','have','my','car','serviced','tomorrow','had','has','done'] },
      { type:'type', prompt:'Complete: "I need to have my eyes ___"', answer:'checked' },
      { type:'gap', prompt:'Complete.',
        sentence:'She had her portrait ___ by a famous artist.',
        options:['painted','paint','painting','paints'], answer:'painted' },
    ]
  },

  // ── PHRASAL VERBS: GET ──
  'phrasal-get-1': {
    topicId: 'phrasal-get', title: 'Meanings of "get"', exercises: [
      { type:'match', prompt:'Match phrasal "get" with its meaning.',
        pairs:[
          ['get you down','depress you'],
          ['get rid of','dispose of'],
          ['get hold of','find / contact'],
          ['get the idea across','communicate successfully'],
        ]},
      { type:'gap', prompt:'Replace the phrase.',
        sentence:'Doesn\'t this gloomy weather ___ you?',
        options:['get you down','get you across','get you up','get you on'], answer:'get you down' },
      { type:'choice', prompt:'Replace "accelerate": "Trains start slow but soon ___"',
        options:['get up speed','get across','get by','get hold of'], answer:'get up speed' },
      { type:'type', prompt:'"To contact/find" a plumber urgently = "get ___ of a plumber"', answer:'hold' },
      { type:'gap', prompt:'Complete.',
        sentence:'I finally ___ the flu I\'ve had for two weeks.',
        options:['got rid of','got hold of','got across','got up'], answer:'got rid of' },
      { type:'choice', prompt:'"I couldn\'t get through to her" means…',
        options:['I couldn\'t reach her on the phone','she ignored me','I couldn\'t teach her','I didn\'t like her'],
        answer:'I couldn\'t reach her on the phone' },
    ]
  },
  'phrasal-get-2': {
    topicId: 'phrasal-get', title: 'More "get" expressions', exercises: [
      { type:'match', prompt:'Match the phrasal "get".',
        pairs:[
          ['get it straight','understand clearly'],
          ['get your own back','take revenge'],
          ['get away with murder','do whatever you want'],
          ['get the sack','be dismissed'],
        ]},
      { type:'gap', prompt:'Replace the underlined.',
        sentence:'Philip\'s teacher lets him ___ murder.',
        options:['get away with','get rid of','get hold of','get up with'], answer:'get away with' },
      { type:'type', prompt:'Complete: "I can\'t ___ ___ of this cold" (shake off)', answer:'get rid' },
      { type:'choice', prompt:'"If you\'re not careful, you\'re going to get the ___" means:',
        options:['sack — be dismissed','idea — understand','hold — find','point — finish'],
        answer:'sack — be dismissed' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'I want to get my own back on him',
        bank:['I','want','to','get','my','own','back','on','him','off','a'] },
      { type:'gap', prompt:'Complete.',
        sentence:'Let me ___ one thing straight: I never lied.',
        options:['get','set','put','make'], answer:'get' },
    ]
  },

  // ── TENSES ──
  'tenses-1': {
    topicId: 'tenses', title: 'Perfect tenses', exercises: [
      { type:'choice', prompt:'Pick the present perfect continuous.',
        options:['I have been reading all day.','I read all day.','I am reading all day.','I was reading all day.'],
        answer:'I have been reading all day.' },
      { type:'gap', prompt:'Complete.',
        sentence:'She ___ here since 2020.',
        options:['has lived','lived','is living','lives'], answer:'has lived' },
      { type:'type', prompt:'Complete: "By next year, they ___ (be) married for 10 years."', answer:'will have been' },
      { type:'bank', prompt:'Build the perfect sentence.',
        answer:'I have just finished my homework',
        bank:['I','have','just','finished','my','homework','had','did','was'] },
      { type:'gap', prompt:'Complete.',
        sentence:'By the time we got there, the film ___ started.',
        options:['had','has','was','did'], answer:'had' },
      { type:'choice', prompt:'Which expresses a result visible now?',
        options:['She has cut her hair.','She cut her hair yesterday.','She cuts her hair.','She was cutting her hair.'],
        answer:'She has cut her hair.' },
    ]
  },
  'tenses-2': {
    topicId: 'tenses', title: 'Past tenses', exercises: [
      { type:'choice', prompt:'Past continuous interrupted by past simple:',
        options:['I was cooking when the phone rang.','I cooked when the phone rang.','I was cook when the phone rang.','I cooking when phone rang.'],
        answer:'I was cooking when the phone rang.' },
      { type:'gap', prompt:'Complete.',
        sentence:'By the time we arrived, the film ___ already started.',
        options:['had','has','was','did'], answer:'had' },
      { type:'type', prompt:'Past perfect: "She ___ (leave) before I arrived."', answer:'had left' },
      { type:'gap', prompt:'Complete.',
        sentence:'While I ___ dinner, she was studying.',
        options:['was cooking','cooked','had cooked','cook'], answer:'was cooking' },
      { type:'choice', prompt:'Which is "used to" for past habits?',
        options:['I used to smoke, but I quit.','I am used to smoking.','I got used to smoking.','I was used to smoke.'],
        answer:'I used to smoke, but I quit.' },
      { type:'bank', prompt:'Build the past sentence.',
        answer:'She had already left when I called',
        bank:['She','had','already','left','when','I','called','has','will','did'] },
    ]
  },

  // ── PEOPLE & CHARACTER ──
  'vocab-people-1': {
    topicId: 'vocab-people', title: 'Types of people', exercises: [
      { type:'match', prompt:'Match the word with its meaning.',
        pairs:[
          ['doer','an active person'],
          ['dabbler','someone who tries many things'],
          ['culture vulture','a culture enthusiast'],
          ['shopaholic','addicted to shopping'],
        ]},
      { type:'choice', prompt:'"He\'s a real doer" means he is…',
        options:['very active','lazy','distracted','clever'], answer:'very active' },
      { type:'type', prompt:'Someone who has "7 Fridays a week" (does a bit of everything) is a ___', answer:'dabbler' },
      { type:'gap', prompt:'Complete with a character word.',
        sentence:'She visits every gallery — a real ___ vulture.',
        options:['culture','brand','music','art'], answer:'culture' },
      { type:'choice', prompt:'Someone who lies on the sofa watching TV all day is a…',
        options:['couch potato','doer','dabbler','culture vulture'],
        answer:'couch potato' },
      { type:'gap', prompt:'Complete.',
        sentence:'She buys clothes she never wears — a total ___.',
        options:['shopaholic','alcoholic','workaholic','culture vulture'], answer:'shopaholic' },
    ]
  },
  'vocab-people-2': {
    topicId: 'vocab-people', title: 'Describing attitude', exercises: [
      { type:'match', prompt:'Match each word with a meaning.',
        pairs:[
          ['absent-minded','forgetful / scattered'],
          ['long-winded','talks too much'],
          ['hooked on','addicted (in a good way)'],
          ['foolish','silly, lacking sense'],
        ]},
      { type:'choice', prompt:'"Absent-minded" describes someone who…',
        options:['forgets easily','is often late','is always angry','is very organised'],
        answer:'forgets easily' },
      { type:'type', prompt:'Synonym of "silly": f___', answer:'foolish' },
      { type:'gap', prompt:'Complete.',
        sentence:'He\'s totally ___ on chess — plays every evening.',
        options:['hooked','pulled','locked','tied'], answer:'hooked' },
      { type:'choice', prompt:'"The black sheep of the family" is…',
        options:['the odd one who disappoints the family','the youngest child','a favourite child','the family pet'],
        answer:'the odd one who disappoints the family' },
      { type:'gap', prompt:'Complete.',
        sentence:'His uncle is ___ rich — bought three houses last year.',
        options:['filthy','small','barely','mere'], answer:'filthy' },
    ]
  },

  // ── TIME & LIFE ──
  'vocab-time-1': {
    topicId: 'vocab-time', title: 'Busy & hectic', exercises: [
      { type:'match', prompt:'Match each expression.',
        pairs:[
          ['full diary','packed schedule'],
          ['hectic','very busy / frantic'],
          ['wrap up','conclude (a meeting, day)'],
          ['rigid','very / extremely (bores me rigid)'],
        ]},
      { type:'gap', prompt:'Complete.',
        sentence:'My schedule this week is totally ___ — back-to-back meetings.',
        options:['hectic','absent','rigid','vague'], answer:'hectic' },
      { type:'type', prompt:'Complete: "I hope we ___ ___ by 12:30." (conclude)', answer:'wrap up' },
      { type:'choice', prompt:'A "full diary" means…',
        options:['a packed schedule','an old notebook','an empty diary','a personal journal'],
        answer:'a packed schedule' },
      { type:'gap', prompt:'Complete.',
        sentence:'Let\'s meet around ___ — maybe 7:10.',
        options:['sevenish','sharp','seven-thirty','seventeen'], answer:'sevenish',
        hint:'approximate time' },
      { type:'choice', prompt:'"His lectures bore me rigid" means they are…',
        options:['extremely boring','quite short','very inflexible','too formal'],
        answer:'extremely boring' },
    ]
  },
  'vocab-time-2': {
    topicId: 'vocab-time', title: 'Talking about ideas', exercises: [
      { type:'match', prompt:'Match each expression.',
        pairs:[
          ['vague idea','rough, approximate'],
          ['stern reproach','serious telling-off'],
          ['talks sense','says reasonable things'],
          ['speak my mind','say what I really think'],
        ]},
      { type:'gap', prompt:'Complete.',
        sentence:'I only have a ___ idea of what he meant.',
        options:['vague','full','stern','rigid'], answer:'vague' },
      { type:'type', prompt:'Complete: "It\'s time I ___ my mind." (express honestly)', answer:'spoke' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'Let us get to the point',
        bank:['Let','us','get','to','the','point','on','in','and'] },
      { type:'choice', prompt:'"A stern reproach" is…',
        options:['a serious telling-off','a quiet compliment','a joke','a friendly greeting'],
        answer:'a serious telling-off' },
      { type:'gap', prompt:'Complete.',
        sentence:'She was ___ from the meeting — nobody knew why.',
        options:['absent','hectic','vague','rigid'], answer:'absent' },
    ]
  },

  // ── DINNER'S ON ME — entertaining & eating out ──
  'dining-1': {
    topicId: 'dining', title: 'Paying the bill', exercises: [
      { type:'choice', prompt:'"Lunch is on me" means…',
        options:['I am paying for everyone','we split the cost','everyone pays for themselves','let\'s ask the waiter'],
        answer:'I am paying for everyone' },
      { type:'gap', prompt:'Complete the offer (informal).',
        sentence:'Don\'t worry about the bill — let me ___ this.',
        options:['get','take','split','make'], answer:'get', hint:'informal: pay the bill this time' },
      { type:'match', prompt:'Match the bill expression with its meaning.',
        pairs:[
          ['split the bill','each pays an equal share'],
          ['go Dutch','everyone pays for themselves'],
          ['be my guest','I am paying for you'],
          ['foot the bill','pay the whole amount'],
        ]},
      { type:'type', prompt:'Complete (formal): "Will you ___ us for dinner?"', answer:'join',
        hint:'invite someone to come along' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'I was wined and dined every night',
        bank:['I','was','wined','and','dined','every','night','feast','out','a'] },
      { type:'choice', prompt:'"To wine and dine someone" means…',
        options:['to entertain them with food and drink','to drink with them','to argue with them','to invite to a wedding'],
        answer:'to entertain them with food and drink' },
      { type:'gap', prompt:'Choose the right phrasing.',
        sentence:'Mark, I\'d like to pay tonight — be my ___.',
        options:['guest','host','date','treat'], answer:'guest' },
      { type:'type', prompt:'Rewrite: "Shall we pay half each?" using "split" → Shall we ___ the bill?', answer:'split' },
    ]
  },
  'dining-2': {
    topicId: 'dining', title: 'Describing service', exercises: [
      { type:'match', prompt:'Match each adjective with what it describes.',
        pairs:[
          ['impeccable','perfect, cannot be faulted'],
          ['sluggish','rather slow'],
          ['courteous','polite'],
          ['overbearing','too confident / inclined to tell people what to do'],
        ]},
      { type:'match', prompt:'Match more service adjectives.',
        pairs:[
          ['sullen','bad-tempered, unwilling to smile'],
          ['brusque','quick and rude'],
          ['off-putting','makes you not want to return'],
          ['go out of their way','do everything possible (for you)'],
        ]},
      { type:'choice', prompt:'Which is a compliment?',
        options:['The service was impeccable.','The service was sluggish.','The waiter was brusque.','The staff were overbearing.'],
        answer:'The service was impeccable.' },
      { type:'gap', prompt:'Complete.',
        sentence:'Their service is generally ___ — the staff are very polite.',
        options:['courteous','sullen','brusque','sluggish'], answer:'courteous' },
      { type:'gap', prompt:'Complete.',
        sentence:'I had to wait 40 minutes — the service was a bit ___.',
        options:['sluggish','impeccable','courteous','overbearing'], answer:'sluggish' },
      { type:'type', prompt:'Adjective for "manner is short and rude": br___', answer:'brusque' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'They go out of their way to be helpful',
        bank:['They','go','out','of','their','way','to','be','helpful','in','on'] },
      { type:'choice', prompt:'A waiter described as "snooty" is…',
        options:['acting superior, looking down on customers','very polite and humble','very quick','very young'],
        answer:'acting superior, looking down on customers' },
      { type:'gap', prompt:'Pick the right word.',
        sentence:'I won\'t go back — the staff were so ___ they refused to smile.',
        options:['sullen','impeccable','courteous','calorie-conscious'], answer:'sullen' },
    ]
  },
  'dining-3': {
    topicId: 'dining', title: 'Food preferences', exercises: [
      { type:'match', prompt:'Match the eater with the description.',
        pairs:[
          ['sweet tooth','loves sweet things'],
          ['fussy eater','has very particular demands'],
          ['teetotal','never drinks alcohol'],
          ['calorie-conscious','watches calories carefully'],
        ]},
      { type:'choice', prompt:'"Savoury" food is…',
        options:['salty in flavour, or with herbs','very sweet','very bitter','tasteless'],
        answer:'salty in flavour, or with herbs' },
      { type:'gap', prompt:'Complete.',
        sentence:'I have a sweet ___ — I can never resist cake.',
        options:['tooth','tongue','spot','heart'], answer:'tooth' },
      { type:'type', prompt:'Complete: "I\'m ___ — I never drink alcohol."', answer:'teetotal' },
      { type:'gap', prompt:'Complete.',
        sentence:'Before we book, do you have any special ___ requirements?',
        options:['dietary','calorie','sweet','foot'], answer:'dietary' },
      { type:'choice', prompt:'"Don\'t overdo it" means…',
        options:['don\'t eat or drink too much','do it more than once','overcook it','eat slowly'],
        answer:'don\'t eat or drink too much' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'Ben is a bit of a fussy eater',
        bank:['Ben','is','a','bit','of','a','fussy','eater','small','foot','an'] },
      { type:'type', prompt:'Synonym: "to ___ the calories" (count carefully)', answer:'count' },
      { type:'gap', prompt:'Choose the right phrase.',
        sentence:'I always have a sweet ___ for dessert.',
        options:['tongue','tooth','foot','arm'], answer:'tongue', hint:'a sweet ___ for dessert — tongue' },
    ]
  },
  'dining-4': {
    topicId: 'dining', title: 'Entertaining at home', exercises: [
      { type:'match', prompt:'Match the entertaining expression with its meaning.',
        pairs:[
          ['take pot luck','eat whatever is there, nothing special'],
          ['bring a bottle','bring wine (usually) to the host'],
          ['dinner party','rather formal dinner with guests'],
          ['get-together','informal group meeting'],
        ]},
      { type:'match', prompt:'Match more host/guest expressions.',
        pairs:[
          ['seconds','a second helping of food'],
          ['say when','tell me when I\'ve served enough'],
          ['nibbles','small snacks (nuts, crisps) before a meal'],
          ['takeaway','ready-cooked meal to take home'],
        ]},
      { type:'gap', prompt:'Complete.',
        sentence:'Why not come round? You\'ll have to take pot ___ — nothing special.',
        options:['luck','meal','food','dish'], answer:'luck' },
      { type:'choice', prompt:'When a host says "say when" they\'re asking you to…',
        options:['tell them when they\'ve poured enough','choose a time','speak louder','wait silently'],
        answer:'tell them when they\'ve poured enough' },
      { type:'gap', prompt:'Complete.',
        sentence:'It\'s not a proper party — just a family get-___.',
        options:['together','round','up','on'], answer:'together' },
      { type:'type', prompt:'Quick informal meal on the way = a quick ___', answer:'bite',
        hint:'"grab a bite to eat"' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'Would anyone like a second helping',
        bank:['Would','anyone','like','a','second','helping','first','more','want'] },
      { type:'choice', prompt:'"Help yourself to some nibbles" means…',
        options:['take some small snacks','order something','wait for the meal','ignore the food'],
        answer:'take some small snacks' },
      { type:'gap', prompt:'Complete.',
        sentence:'Shall we get a ___ instead of cooking tonight?',
        options:['takeaway','potluck','nibble','seconds'], answer:'takeaway' },
    ]
  },

  // ── FEELINGS ──
  'feelings-1': {
    topicId: 'feelings', title: 'Feel + noun / + adj', exercises: [
      { type:'match', prompt:'Match each "feel" expression with its meaning.',
        pairs:[
          ['feel free','you can do it without asking'],
          ['have a feel for','have a natural talent for'],
          ['get the feel of','become comfortable with (something new)'],
          ['feel it in my bones','sense something instinctively'],
        ]},
      { type:'choice', prompt:'"She has a feel for languages" means she…',
        options:['has a natural talent for languages','dislikes languages','is studying them now','teaches languages'],
        answer:'has a natural talent for languages' },
      { type:'gap', prompt:'Complete.',
        sentence:'Please, ___ free to have some tea or coffee.',
        options:['feel','have','take','make'], answer:'feel' },
      { type:'type', prompt:'Complete: "You\'ll soon get the ___ of it." (become comfortable)', answer:'feel' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'I can feel it in my bones',
        bank:['I','can','feel','it','in','my','bones','my','heart','for'] },
      { type:'choice', prompt:'"I\'m starting to feel my age" means…',
        options:['I notice the effects of getting older','I look young','I feel exhausted','I want to retire'],
        answer:'I notice the effects of getting older' },
      { type:'gap', prompt:'Complete.',
        sentence:'I have mixed ___ about the new boss.',
        options:['feelings','feels','feels','feel'], answer:'feelings' },
    ]
  },
  'feelings-2': {
    topicId: 'feelings', title: 'Hard feelings & sensitivity', exercises: [
      { type:'choice', prompt:'"I hope you have no hard feelings about it" means…',
        options:['I hope you are not upset/angry with me','I hope you remember it','I hope you don\'t care','I hope you understand'],
        answer:'I hope you are not upset/angry with me' },
      { type:'gap', prompt:'Complete.',
        sentence:'She\'s a very sensitive girl — please don\'t hurt her ___.',
        options:['feelings','feel','mind','heart'], answer:'feelings' },
      { type:'match', prompt:'Match each expression.',
        pairs:[
          ['hurt someone\'s feelings','upset them emotionally'],
          ['no hard feelings','no resentment'],
          ['mixed feelings','partly positive, partly negative'],
          ['didn\'t feel a thing','noticed nothing at all'],
        ]},
      { type:'type', prompt:'Complete: "I didn\'t ___ a thing" (= I didn\'t notice anything)', answer:'feel' },
      { type:'choice', prompt:'"I know just how you feel" expresses…',
        options:['empathy','disagreement','curiosity','authority'],
        answer:'empathy' },
      { type:'gap', prompt:'Choose the right word.',
        sentence:'I have ___ feelings about it — partly happy, partly sad.',
        options:['mixed','hard','small','vague'], answer:'mixed' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'I do not want to hurt her feelings',
        bank:['I','do','not','want','to','hurt','her','feelings','feel','him'] },
    ]
  },
  'feelings-3': {
    topicId: 'feelings', title: 'Decisions & reactions', exercises: [
      { type:'match', prompt:'Match the expression with its meaning.',
        pairs:[
          ['on second thoughts','after reconsidering'],
          ['I wasn\'t thinking straight','I wasn\'t reasoning clearly'],
          ['vote with my feet','show disapproval by leaving / not returning'],
          ['take a plunge','make a brave decision'],
        ]},
      { type:'gap', prompt:'Complete.',
        sentence:'___ thoughts, I think I will come after all.',
        options:['On second','At second','In second','By second'], answer:'On second' },
      { type:'choice', prompt:'"I could do with a cup of coffee" means…',
        options:['I would really like a coffee now','I dislike coffee','I have already had coffee','I make good coffee'],
        answer:'I would really like a coffee now' },
      { type:'type', prompt:'Complete: "If it\'s any ___, the train arrives in five minutes." (comfort)', answer:'consolation' },
      { type:'gap', prompt:'Complete.',
        sentence:'I voted with my ___ and left the restaurant.',
        options:['feet','hands','heart','head'], answer:'feet' },
      { type:'choice', prompt:'A "melting pot" describes…',
        options:['a place where many cultures mix','a kitchen pot','a heated argument','a hot day'],
        answer:'a place where many cultures mix' },
      { type:'bank', prompt:'Build the sentence.',
        answer:'I was not thinking straight at the time',
        bank:['I','was','not','thinking','straight','at','the','time','clear','round'] },
      { type:'type', prompt:'Complete: "She decided to take a ___" (make a brave decision)', answer:'plunge' },
      { type:'gap', prompt:'Complete.',
        sentence:'The colour of the dress was a soft ___ purple — barely a tint.',
        options:['pale','jet','shocking','rock'], answer:'pale' },
    ]
  },
};

// ─── VOCABULARY CARDS (flashcards) ───────────────────────────
const VOCAB_CARDS = [
  // Time & Life
  { en:'full diary',         def:'packed schedule',                                  ex:'My diary is full this week — back-to-back meetings.' },
  { en:'hectic',             def:'extremely busy, frantic',                          ex:'Things are totally hectic at work right now.' },
  { en:'sevenish',           def:'approximately seven',                              ex:'Let\'s meet around sevenish.' },
  { en:'wrap up',            def:'to conclude (a meeting or the day)',               ex:'I hope we can wrap up by six.' },
  { en:'rigid',              def:'extremely / strongly (as in "bores me rigid")',    ex:'His lectures bore me rigid.' },
  { en:'absent',             def:'not present; not at a meeting',                    ex:'She was absent from the meeting.' },

  // People & Character
  { en:'hooked on',          def:'addicted (in a good way)',                         ex:'She\'s hooked on crime novels lately.' },
  { en:'doer',               def:'an active, decisive person',                       ex:'He\'s a real doer — always building something.' },
  { en:'dabbler',            def:'someone who tries many things superficially',      ex:'Ask a dabbler — they\'ve tried everything once.' },
  { en:'culture vulture',    def:'someone obsessed with art / culture',              ex:'Take her to the Tate — she\'s a culture vulture.' },
  { en:'couch potato',       def:'physically inactive person who watches TV',        ex:'Stop being a couch potato — let\'s go out!' },
  { en:'shopaholic',         def:'someone addicted to shopping',                     ex:'Laura\'s a shopaholic; her closet is overflowing.' },
  { en:'absent-minded',      def:'forgetful, scattered',                             ex:'He\'s so absent-minded he lost his keys twice today.' },
  { en:'foolish',            def:'silly, lacking good sense',                        ex:'It was foolish of me to trust him.' },

  // Free Time & Leisure
  { en:'rewarding',          def:'gives positive experiences',                       ex:'Volunteering is very rewarding.' },
  { en:'fruitful',           def:'produces good results',                            ex:'We had a fruitful discussion.' },
  { en:'lucrative',          def:'makes a lot of money',                             ex:'Photography became a lucrative pursuit for her.' },
  { en:'therapeutic',        def:'healthy for body or mind',                         ex:'Painting is a therapeutic activity.' },
  { en:'time-consuming',     def:'takes a long time to do',                          ex:'Running a committee is time-consuming.' },
  { en:'heavily into',       def:'very interested in (informal)',                    ex:'He\'s heavily into downhill skiing.' },
  { en:'went off',           def:'lost interest in',                                 ex:'I went off football and started golf.' },
  { en:'get up to',          def:'to do (informal, at weekends etc.)',               ex:'What do you get up to at weekends?' },
  { en:'lock oneself away',  def:'to isolate oneself from the world',                ex:'She locks herself away at her computer.' },

  // Using Language
  { en:'long-winded',        def:'dragging on too long when speaking',               ex:'His speeches are always long-winded.' },
  { en:'talks sense',        def:'says reasonable, sensible things',                 ex:'Listen to Maya — she talks sense.' },
  { en:'speak my mind',      def:'say what I truly think',                           ex:'I\'d like to speak my mind, if I may.' },
  { en:'get to the point',   def:'address the main matter',                          ex:'Stop rambling and get to the point.' },
  { en:'in a nutshell',      def:'briefly / in short',                               ex:'In a nutshell, we need more time.' },
  { en:'start the ball rolling', def:'begin the discussion',                         ex:'Who\'s going to start the ball rolling?' },
  { en:'reproach',           def:'to blame / scold gently',                          ex:'She reproached him for being late.' },
  { en:'stern reproach',     def:'a serious telling-off',                            ex:'He received a stern reproach from the boss.' },
  { en:'vague idea',         def:'rough, approximate understanding',                 ex:'I only have a vague idea of what he meant.' },
  { en:'talks down',         def:'speaks condescendingly',                           ex:'I hate when he talks down to junior staff.' },
  { en:'inferior',           def:'lower in status / quality',                        ex:'Don\'t treat anyone as inferior.' },
  { en:'cross-purposes',     def:'mutually misunderstanding',                        ex:'We were talking at cross-purposes.' },
  { en:'wrong end of the stick', def:'misunderstanding',                             ex:'You\'ve got the wrong end of the stick.' },
  { en:'get a word in edgeways', def:'interrupt to speak',                           ex:'I couldn\'t get a word in edgeways.' },
  { en:'talk shop',          def:'talk about work',                                  ex:'No talking shop at dinner!' },
  { en:'small talk',         def:'light, social conversation',                       ex:'She\'s great at small talk.' },

  // Emphasising
  { en:'bone dry',           def:'completely dry',                                   ex:'The towel was bone dry.' },
  { en:'rock hard',          def:'extremely hard',                                   ex:'The bread was rock hard.' },
  { en:'stone cold',         def:'very cold',                                        ex:'Your coffee is stone cold.' },
  { en:'piping hot',         def:'very hot',                                         ex:'Piping hot soup, just how I like it.' },
  { en:'razor-sharp',        def:'very sharp (wit/mind)',                            ex:'She has a razor-sharp sense of humour.' },
  { en:'crystal clear',      def:'completely clear / obvious',                       ex:'It\'s crystal clear what he meant.' },
  { en:'filthy rich',        def:'extremely wealthy',                                ex:'His uncle is filthy rich.' },
  { en:'squeaky-clean',      def:'spotless, scandal-free',                           ex:'A squeaky-clean image matters in politics.' },
  { en:'in broad daylight',  def:'during the day when visible',                      ex:'She was robbed in broad daylight.' },
  { en:'rock bottom',        def:'the lowest point',                                 ex:'Things have hit rock bottom.' },
  { en:'small fortune',      def:'a large sum of money',                             ex:'The cameras cost a small fortune.' },
  { en:'mere pittance',      def:'a very small amount',                              ex:'They were fined a mere pittance.' },
  { en:'bare-faced lies',    def:'obvious, shameless untruths',                      ex:'Don\'t tell me bare-faced lies.' },
  { en:'full stop',          def:'there is nothing more to say',                     ex:'He\'s guilty, full stop.' },
  { en:'stark naked',        def:'completely naked',                                 ex:'He stood there stark naked.' },

  // Phrasal: Get
  { en:'get it across',      def:'communicate successfully',                         ex:'It\'s hard to get the idea across.' },
  { en:'get you down',       def:'to depress you',                                   ex:'Don\'t let the weather get you down.' },
  { en:'get rid of',         def:'dispose of / eliminate',                           ex:'I can\'t get rid of this cold.' },
  { en:'get the sack',       def:'to be dismissed / fired',                          ex:'If you\'re not careful, you\'ll get the sack.' },
  { en:'get your own back',  def:'take revenge',                                     ex:'He wants to get his own back on them.' },
  { en:'get up speed',       def:'accelerate',                                       ex:'The train got up speed quickly.' },
  { en:'get hold of',        def:'find / contact',                                   ex:'I\'m trying to get hold of the plumber.' },
  { en:'get away with',      def:'escape punishment / do what you want',             ex:'He gets away with murder at home.' },

  // Colour — specific shades
  { en:'pitch black',        def:'intensely black (used of darkness)',               ex:'The room was pitch black.' },
  { en:'jet black',          def:'intensely black (used of hair, eyes)',             ex:'She has jet black hair.' },
  { en:'scarlet',            def:'brilliant red',                                    ex:'Her dress was scarlet.' },
  { en:'crimson',            def:'strong deep red',                                  ex:'A crimson sunset.' },
  { en:'shocking pink',      def:'extremely bright pink',                            ex:'Shocking pink is back in fashion.' },
  { en:'navy',               def:'dark blue (used of clothes)',                      ex:'A navy blazer looks professional.' },
  { en:'turquoise',          def:'greenish blue (fabric, sea)',                      ex:'The sea was a stunning turquoise.' },
  { en:'auburn',             def:'red-brown (used of hair)',                         ex:'She has lovely auburn hair.' },
  { en:'chestnut',           def:'deep reddish brown (hair, horses)',                ex:'A chestnut mare.' },
  { en:'mousy',               def:'dull light brown (hair only)',                    ex:'Her mousy hair suited her quiet nature.' },
  { en:'beige',              def:'a light creamy brown',                             ex:'Beige walls feel calm.' },
  { en:'ginger',             def:'orangey red (hair, cats)',                         ex:'A ginger cat curled up in the sun.' },

  // Colour — talking about colour
  { en:'tinge',              def:'a slight shade or trace',                          ex:'A tinge of green in the water.' },
  { en:'electric blue',      def:'extremely bright, glowing blue',                   ex:'Her electric blue eye shadow.' },
  { en:'vivid',              def:'strong, bright (colour or imagination)',           ex:'Vivid red poppies in the field.' },
  { en:'pastel',             def:'pale shade of a colour',                           ex:'Pastel yellow is soothing.' },
  { en:'fluorescent',        def:'glowing bright colours',                           ex:'Fluorescent vests for cyclists.' },
  { en:'monochrome',         def:'uses only one colour',                             ex:'A monochrome photo of the city.' },

  // Colour metaphors
  { en:'green with envy',    def:'very jealous',                                     ex:'He was green with envy over the new car.' },
  { en:'to go green',        def:'to feel nauseous',                                 ex:'He went green on the rollercoaster.' },
  { en:'to look green',      def:'to look ill / sickly',                             ex:'You look green — are you OK?' },
  { en:'nausea',             def:'the feeling of being sick',                        ex:'The smell gave her nausea.' },
  { en:'once in a blue moon', def:'very rarely',                                     ex:'We meet once in a blue moon.' },
  { en:'out of the blue',    def:'unexpectedly',                                     ex:'She called me out of the blue.' },
  { en:'feel blue',          def:'feel sad / depressed',                             ex:'I\'ve been feeling blue all week.' },
  { en:'blue-collar workers',def:'physical / manual workers',                        ex:'Blue-collar workers built this city.' },
  { en:'white-collar workers',def:'office workers',                                  ex:'White-collar work dominates downtown.' },
  { en:'red carpet treatment', def:'special VIP welcome',                            ex:'They rolled out the red carpet treatment.' },
  { en:'red-letter day',     def:'an important / special day',                       ex:'The day we met was a red-letter day.' },
  { en:'to see red',         def:'to become very angry',                             ex:'When he lied, I saw red.' },
  { en:'red-point of view',  def:'left-wing in politics',                            ex:'The paper takes a red-point of view.' },
  { en:'paint the town red', def:'go out and celebrate noisily',                     ex:'Let\'s paint the town red tonight!' },
  { en:'in the red',         def:'in debt',                                          ex:'The company is deeply in the red.' },
  { en:'wet behind the ears',def:'inexperienced, naive',                             ex:'He\'s still wet behind the ears.' },
  { en:'black sheep',        def:'the odd / disappointing one in a family',          ex:'My brother is the black sheep of the family.' },
  { en:'black market',       def:'illegal trade',                                    ex:'Cigarettes were sold on the black market.' },
  { en:'a black mark',       def:'a negative record against someone',                ex:'That\'ll be a black mark against my name.' },
  { en:'as black as thunder',def:'very angry (expression)',                          ex:'His face was as black as thunder.' },
  { en:'grey area',          def:'an unclear situation',                             ex:'The law here is a grey area.' },
  { en:'grey matter',        def:'brains, intellect',                                ex:'Use your grey matter!' },
  { en:'grey cells',         def:'the brain (humorous)',                             ex:'Put on your grey cells and think.' },
  { en:'white as a sheet',   def:'very pale with fear',                              ex:'She went white as a sheet.' },
  { en:'white knuckle',      def:'terrifying (e.g. a ride)',                         ex:'A white knuckle ride at the fair.' },

  // Dinner's on me — entertaining & eating out
  { en:'split the bill',     def:'each person pays an equal share',                  ex:'Shall we split the bill?' },
  { en:'go Dutch',           def:'everyone pays for themselves',                     ex:'Let\u2019s go Dutch this time.' },
  { en:'foot the bill',      def:'pay the whole amount',                             ex:'Her dad footed the bill.' },
  { en:'it\u2019s on me',    def:'I am paying for everyone',                         ex:'Don\u2019t argue \u2014 dinner is on me.' },
  { en:'let me get this',    def:'informal: I\u2019ll pay the bill this time',       ex:'Put your wallet away, let me get this.' },
  { en:'be my guest',        def:'I am paying for you / please go ahead',            ex:'Mark, be my guest \u2014 I insist.' },
  { en:'wined and dined',    def:'invited out and entertained with food and drink',  ex:'I was wined and dined every night by the New York office.' },
  { en:'impeccable',         def:'perfect, cannot be faulted',                       ex:'The service at Bella Roma is impeccable.' },
  { en:'sluggish',           def:'slow, lacking in energy',                          ex:'The service was a bit sluggish.' },
  { en:'courteous',          def:'polite',                                           ex:'A courteous waiter at the Bengal.' },
  { en:'overbearing',        def:'too confident, telling people what to do',         ex:'The staff were a bit overbearing.' },
  { en:'sullen',             def:'bad-tempered, unwilling to smile',                 ex:'The waiters at Sea View were sullen.' },
  { en:'brusque',            def:'quick and rude in manner',                         ex:'A brusque tone with the customers.' },
  { en:'off-putting',        def:'making you not want to come back',                 ex:'I found his manner very off-putting.' },
  { en:'go out of one\u2019s way', def:'do everything possible to help',             ex:'They go out of their way to give you what you want.' },
  { en:'snooty',             def:'acting superior; looks down on others',            ex:'That snooty head-waiter addresses everyone formally.' },
  { en:'sweet tooth',         def:'a love of sweet things',                          ex:'I have a sweet tooth \u2014 I can never resist cake.' },
  { en:'savoury',            def:'salty in flavour, or with herbs',                  ex:'I like to end the meal with something savoury.' },
  { en:'calorie-conscious',  def:'someone who watches calories carefully',           ex:'I have to be a bit calorie-conscious these days.' },
  { en:'fussy eater',        def:'a person with very particular food demands',       ex:'Ben\u2019s a bit of a fussy eater.' },
  { en:'teetotal',           def:'never drinks alcohol',                             ex:'My great aunt is teetotal.' },
  { en:'dietary requirements', def:'special needs / things someone cannot eat',      ex:'Do you have any particular dietary requirements?' },
  { en:'overdo it',          def:'eat or drink too much',                            ex:'I don\u2019t want to overdo it tonight.' },
  { en:'take pot luck',      def:'eat whatever is there; nothing special',           ex:'Come home with us \u2014 you\u2019ll have to take pot luck.' },
  { en:'bring a bottle',     def:'usually means bring a bottle of wine',             ex:'Shall I bring a bottle?' },
  { en:'dinner party',       def:'rather formal dinner with guests',                 ex:'No, it isn\u2019t a dinner party \u2014 just a get-together.' },
  { en:'get-together',       def:'informal group of people meeting for a meal',      ex:'Just a small family get-together.' },
  { en:'seconds',            def:'a second helping or serving of a dish',            ex:'Does anyone want seconds?' },
  { en:'say when',           def:'tell me when I\u2019ve poured/served enough',      ex:'Say when \u2014 don\u2019t be shy.' },
  { en:'nibbles',            def:'small snacks (nuts, crisps) before a meal',        ex:'Help yourself to some nibbles.' },
  { en:'grab a bite',        def:'have a quick, informal meal',                      ex:'We can grab a bite on the way.' },
  { en:'takeaway',           def:'ready-cooked meal to take home',                   ex:'We could get a takeaway when we get there.' },
  { en:'make yourself at home', def:'an informal welcome inviting comfort',          ex:'Just make yourself at home while you\u2019re waiting.' },

  // Feelings
  { en:'feel free',          def:'you can do something without asking',              ex:'Feel free to have some tea or coffee.' },
  { en:'have a feel for',    def:'have a natural talent for something',              ex:'Dawn clearly has a feel for languages.' },
  { en:'get the feel of',    def:'become comfortable with something new',            ex:'You\u2019ll soon get the feel of it.' },
  { en:'feel it in my bones',def:'sense something instinctively',                    ex:'I can feel it in my bones \u2014 it\u2019s going to rain.' },
  { en:'mixed feelings',     def:'partly positive, partly negative',                 ex:'I have mixed feelings about the move.' },
  { en:'no hard feelings',   def:'no resentment after a disagreement',               ex:'I hope you have no hard feelings about it.' },
  { en:'hurt someone\u2019s feelings', def:'upset them emotionally',                 ex:'I don\u2019t want to hurt her feelings.' },
  { en:'feel my age',        def:'notice the effects of getting older',              ex:'I\u2019m starting to feel my age.' },
  { en:'didn\u2019t feel a thing', def:'noticed nothing at all (e.g. anaesthetic)',  ex:'I didn\u2019t feel a thing during the procedure.' },
  { en:'I know just how you feel', def:'an expression of empathy',                   ex:'I know just how you feel \u2014 I\u2019ve been there.' },
  { en:'phew!',              def:'expresses relief',                                 ex:'Phew! I can\u2019t keep up with you.' },
  { en:'consolation',        def:'something that gives comfort',                     ex:'If it\u2019s any consolation, it\u2019s nearly over.' },
  { en:'on second thoughts', def:'after reconsidering',                              ex:'On second thoughts, I\u2019ll come too.' },
  { en:'I wasn\u2019t thinking straight', def:'I wasn\u2019t reasoning clearly',     ex:'Sorry, I wasn\u2019t thinking straight at the time.' },
  { en:'vote with my feet',  def:'show disapproval by leaving / not returning',      ex:'The food was bad, so I voted with my feet.' },
  { en:'take the plunge',    def:'finally make a brave decision',                    ex:'After years of doubt, she took the plunge.' },
  { en:'I could do with',    def:'I would really like (informal)',                   ex:'I could do with a cup of coffee right now.' },
  { en:'unconditional love', def:'love with no conditions attached',                 ex:'A parent\u2019s love is often unconditional.' },
  { en:'melting pot',        def:'a place where many cultures mix together',         ex:'New York is a real melting pot.' },
  { en:'pale purple',        def:'a soft, light shade of purple',                    ex:'Her scarf was a beautiful pale purple.' },
];

window.TOPICS = TOPICS;
window.LESSONS = LESSONS;
window.VOCAB_CARDS = VOCAB_CARDS;
